spring.application.name=hospital

# ?? Server ??
server.port=8082

# ?? Database ??
spring.datasource.url=jdbc:mysql://localhost:3306/hospitaldb
spring.datasource.username=root
spring.datasource.password=pass@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ?? JPA / Hibernate ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ?? JWT ??
jwt.secret=hospital-super-secret-key-256-bit-minimum!!
jwt.expiration=36000000

# ?? Disable open-in-view warning ??
spring.jpa.open-in-view=false